### PR TITLE
Refactor of build process

### PR DESCRIPTION
**Pull request by mathuin**
Removed Toolbar and JSI plugins.

Updated build process to Mono standard.

Cleaned up other files.

### CODE REVIEW

**Comment by mathuin** [comment]
**Please** test this.  I know that it appears to work in RPM -- "disco mode" is neat -- but I do not use the Toolbar mode so I do not know what it's supposed to do.

I do not have Blizzy's Toolbar installed, and the vv icon does show up on the stock toolbar.  When I left-click the toolbar button, a "Vessel View" window appears with the same basic contents as the RPM version but without controls.  Right-clicking brings up a configuration menu.  Reverting to launch brings up a new icon every time -- but only the bottom icon does anything.

If that's normal behavior, then this pull request will probably be useful to toolbar users.

**Comment by mathuin** [comment]
Forgot to mention that this PR is in response to #7. :-)

**Comment by mathuin** [comment]
This PR is definitely a WIP.

With Blizzy installed, the plugin does not install itself in the stock tool bar.  It can be installed into the Blizzy tool bar.  Without RPM installed, the buttons on the Blizzy tool bar do nothing.

With RPM installed, the plugin installs itself in the stock tool bar, and the buttons do work, but reverting the flight causes it to be installed multiple times -- something which doesn't happen when Blizzy is installed.

Work to do:
1. Figure out why reverting causes a duplicate icon to be posted and fix that.
2. Remove dependency on RPM so addon works from Blizzy or stock toolbar without RPM.

**Comment by mathuin** [comment]
Okay!  I replaced the button code with something based on code from Alshain01/KSP-AdvancedTweakablesButton (MIT license).

There are four installation cases that I have tested:
1. Stock (no Blizzy and no RPM):  the icon appears in the toolbar and responds correctly to left-click and right-click.
2. Blizzy, no RPM:   no icon in the toolbar, both icons available in Blizzy's toolbar, both icons work.
3. RPM, no Blizzy:  icon in toolbar behaving as in the first case plus the RPM Vessel button works.
4. Blizzy and RPM:  same as the second case plus the RPM Vessel button works.

Please please test this.  If it does work, you should be able to replace all the VesselView addons in CKAN with this one, with Blizzy and RPM as recommended addons instead of dependencies.

**Comment by linuxgurugamer** [comment]
You have changed  186 files. 
I hve to review all changes before I accept, it would be nice if you told me what files were changed and why the change was made.

Also, the build process which you so flippantly dismissed and changed was there for a reason.  My reason, for my purposes. 
Among other things the Gamedata files are needed to be committed, for my jenkins server which is expecting them there.
Reformating files generates huge files for me to look at, ans is a waste of my time, since i dont know what is a format change and what is a real change.
I can go along with removing JSI from the gamedata, that was an old oversight, but you should have done that in a separate PR
Renaming files just because you want to rename them is not appreciated

Sorry, I cant accept this.  You are doing too much with no explanation.
Before you redo read this:
1.  If you was to remove JSI, ok, but do it in its own branch and its own PR
2. Dont rename files if they are not needed to be renamed.  You can suggest but dont do it.
3. It seems you’ve done several things, again do each in its own branch if you can, and please avoid reformating files, it makes the diffs much larger.
4. Don’t change the build process

**Comment by mathuin** [comment]
The biggest reason I changed the build process is because it didn't work on my system and it was non-standard.  There was no flippancy intended in my terse comment.  I am sorry if that bothered you.

I am curious as to why Jenkins expects the GameData files to be committed there when they are installed there.  That's not normal behavior in my experience with Jenkins, but you probably have a different configuration than I expected.  If that's working and you don't want to change it, I understand.

The UI shows 186 files changed, that is true.  I did not know you would want a detailed summary of changes.
 * I modified .gitignore to reflect the changes in the build process that I made and to avoid committing the GameData files which were being copied there upon build.
 * I removed 2 files in .vs that were breaking the build for me.
 * I removed 10 files for 000_Toolbar and 103 files for JSI which were causing the problem which inspired me to write the pull request.
 * I removed 3 files in AVCinfo because they were no longer referencing active code.
 * I renamed the license file to match that usually seen on GitHub.
 * I rewrote the README file to match that usually seen on GitHub.
 * I removed the versions of both those files which were committed in GameData because they're overwritten every time the build process runs.
 * The .csproj changes were made to make the build process OS-agnostic by replacing hardcoded Windows drive letters and paths with relative paths based on a symlink which works on Windows, Mac and Linux
 * The .cs changes were to implement the feature itself which was freeing the dependency on the two included plugins which was preventing me from using this plugin.
 * The single least necessary change was modifying the changelog.  That one was probably gratuitious.

The purpose of the pull request was to suggest changes, ranging from trivial to significant.  That's why I called it a work in progress.  If you see any benefit in any of the changes, please let me know.  I will be happy to work with you to reconcile differences.

**Comment by linuxgurugamer** [comment]
It's my build process, on my Jenkins server.  Which is a Linux box.  Which is expecting certain files, in certain formats.

186 files is a lot to go through.

Would it be really hard to redo this, in several new branches, to break out each separate set of changes.  I do appreciate the work you did, but it's just unreasonable to expect someone to gp through 186 files, dealing with so many different sets of changes.  If you did this, then it would be easier for me to include or exclude them.
Regarding the .csproj, please don't change the one I have.  Feel free to add it as a second one which you use, that will give me the ability to see what you did without breaking my systems

**Comment by mathuin** [comment]
The problem with redoing this pull request is that without the build process changes, I just can't build the plugin on my system.  The .csproj files as written do not compile for me.  Using `VesselView\VesselView\VesselView.csproj` as an example:
 * The output paths were set to the plugin directory, which will destroy the most recent build if it fails.
 * The DLL references were hard-coded to Windows drive paths.
 * The text templating stuff had hard-coded Windows drive paths as well and doesn't work on my 
system, and turns out to not serve a purpose in the final plugin as far as I can tell -- what does it do?

Of those observations, one is arguably style-related but the other two actually break the build for me.

The changes I made:
 * Include the KSP_Dir property which lets me use symlinks instead of hard-coded paths, something that works on Windows, MacOS and Linux.
 * Points the output path to a config-specific directory under the checkout so I can compare DLLs from Debug and Release without writing over the final plugin directory.
 * Removes the text templating stuff.
 * Uses the AfterBuild target to copy files into place, which will work on Windows, MacOS, and Linux.

Of those changes, one is style-related and the other three actually make the build run.

I am curious about your Jenkins server's configuration file, and would like to learn more if you're interested in sharing, especially if it's something that I can learn to use here when working on plugins.

Here's a script I used to make a flat directory of CS files for diff purposes:
```
#!/bin/bash
rm -rf ../flat
mkdir ../flat/ ../flat/master ../flat/refactor-build
git checkout master
for file in `find V[eV]* -type f -name "*.cs" -print | xargs echo`; do dash=`echo $file | sed -e "s|/|-|g" -e "s|^|../flat/master/|"` && cp $file $dash; done
git checkout refactor-build
for file in `find VesselView -type f -name "*.cs" -print | xargs echo`; do dash=`echo $file | sed -e "s|/|-|g" -e "s|^VesselView-|../flat/refactor-build/|"` && cp $file $dash; done
```

When I `diff -rw ../flat/master ../flat/refactor-build`, I can see that only two files were actually changed:  `ToolbarWrapper.cs` and `VesselViewPlugin.cs`.  Both files were reformatted on save, though, while I was working on them.  In fact, I don't think there are any actual changes in `ToolbarWrapper.cs`!  Atom does that and I'm sorry for that -- if that keeps you from accepting this pull request, I will fix it.  Also, three files were added:  `AppLauncher.cs`, `IButtonBar.cs`, and `Toolbar.cs`.  And as mentioned above, five files were removed:  the `AssemblyVersion.cs` files.  I removed them when I removed the text templating stuff, and they're generated files so it's not good practice to commit them.

Anyway, the changes in `VesselViewPlugin.cs` were to abstract out the toolbar concept to apply to either stock or Blizzy's.  This required me to make the `ViewerSettings` public as it needs to be triggered from outside this package by the code in the new files.  It also meant removing the code which previously initialized the toolbar and manipulated the settings.

If you would like a new pull request with just the one changed file and three additional files, I'm happy to do it.  I will be unable to test the changes locally so I can't guarantee they'll work.  Alternatively, if you want to copy those four files from my branch into your own branch and modify `VesselViewPlugin.csproj` to suit, you will be able to test-drive my changes and tell me what you think.  I apologize if that means making extra work for you, but based on your build process I think that's probably the most effective way to find out if my changes work for you!

Now off to figure out how to tell Atom not to reformat code on save...

**Comment by linuxgurugamer** [comment]
Maybe you should ask before doing?

The text templating is used to put the mod version into the assembly code, so that when someone posts a log file asking for help, I can see exactly which version of the mod they are using.
The assemblyversion.cs is included since I don't have  the text templating working on Linux yet, so I commit to after doing local build
The Afterbuild doesn't work with the Jenkins server I have setup.  I have Mono installed along with KSP, and it's a command line compile step.
The deploy.bat and buildRelease.bat are used by myself on my local system.  Obviously they are set up for my own system, but they should (or will) be parametarized so to remove the hard-coded addresses.

After reading your notes, it seems that you adapted the build process to something you are familiar with.  That's fine for yourself, but when you are working with someone else's repo, you need to adapt to their process.

And, given the changes you made, would have been better to commit to a branch rather than the master.  I'm going to create a new branch and merge this into that, so I can examine the changes without changing the current mod.  Since you've identified the changed c# files, it will be fairly easy for me to pull them out.

**Comment by linuxgurugamer** [comment]
I'll look at this when I can, but am busy with other stuff right now

**Comment by mathuin** [comment]
It's common on GitHub to send unsolicited pull requests as a way to suggest an improvement.  I based my changes on your master branch, so that's why the pull request was connected to master.  I am pleased that my explanation helped, and I hope to see the functionality in the master branch sometime soon.

**Comment by linuxgurugamer** [comment]
Well, it's always polite to contact the author/owner first, and explain what you are going to do.  I appreciate people submitting PRs, and usually it just takes a few minutes to review, but this is the second large PR I've gotten in the past week, and since it isn't my job, it takes the back burner.  The other one at least contacted me first, so I knew what was coming.
Again, changing a build process is much more intrusive than changing code.  You could have easily changed the files locally, and just committed the code changes
Anyway, I'll try to look at this sometime later this week

**Pull request merged**
