### PR TITLE
Moves menu pointer to beginning of line

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Just an FYI, I fixed the InstallChecker this morning.  Could you remove that from your PR please?

**Comment by Kerbas-ad-astra** [comment]
Yes, it's removed.  (That was PR #12, this is 13.)

**Comment by linuxgurugamer** [comment]
Ok, thanks.  I've review this evening

**Comment by linuxgurugamer** [comment]
Will I need to have RPM available to recompile it?  or MAS?

**Comment by Kerbas-ad-astra** [comment]
You won't need either.  Just JSIPartUtilities.  MAS has a configuration file that tells it what DLL and methods to use to put VesselViewer on screen, so there's no compile dependency in either direction.

**Comment by linuxgurugamer** [comment]
I'll try it, but I recall that I had compile errors yesterday when updating the mod, because RPM wasn't available.

**Pull request merged**
